### ISSUE TITLE
Sanitation Collection Day

### ISSUE THREAD

**Issue by dshanske** [elahd/ha-nyc311#1]
Wondering if there could be some sort of option to set when your collection is, so it would compare that to the day that trash/recycling is actually being collected.

The API doesn't have anything to figure that out automatically. The closest I found was the DSNY's API, https://a827-donatenyc.nyc.gov/DSNYGeoCoder/api/DSNYCollection/CollectionSchedule?address=123 Main St, 10001

**Comment by dshanske** [comment]
Was surprised to find this one too. https://a827-donatenyc.nyc.gov/DSNYApi/api/Holidays/CheckSanitationHolidayToday

**Comment by elahd** [comment]
Thanks for posting those links. Let's merge this conversation into #3.
