### ISSUE TITLE
311 Complaints

### ISSUE THREAD

**Issue by HiTechTLS** [elahd/ha-nyc311#2]
Could this be used to be identify if a 311 call was logged against an address? I think it's from the same database.

https://nycopendata.socrata.com/d/erm2-nwe9/visualization

https://portal.311.nyc.gov/check-status/

**Comment by elahd** [comment]
Hey -- unfortunately, that's a different API. This project is also just focused on pulling scheduling exceptions for basic public services.

The Socrata-hosted APIs you linked to have decent documentation and integrations, though. Take a look at https://dev.socrata.com/foundry/data.cityofnewyork.us/erm2-nwe9.
