### ISSUE TITLE
Encountered Unknown Service or Status

### ISSUE THREAD

**Issue by ghost** [elahd/ha-nyc311#9]
2022-05-16 14:27:27 ERROR (MainThread) [nyc311calendar.api] 
Encountered unknown service or status. Please report this to the developers using the "Unknown Service or Status" bug template at https://github.com/elahd/nyc311calendar/issues/new/choose.
2022-05-16 14:27:27 ERROR (MainThread) [custom_components.nyc311] Unexpected error fetching nyc311 data: 
  File "/usr/local/lib/python3.9/site-packages/nyc311calendar/api.py", line 209, in __async_calendar_update
  File "/config/custom_components/nyc311/__init__.py", line 39, in async_update_data
  File "/usr/local/lib/python3.9/site-packages/nyc311calendar/api.py", line 168, in get_calendar
  File "/usr/local/lib/python3.9/site-packages/nyc311calendar/api.py", line 224, in __async_calendar_update
nyc311calendar.api.NYC311API.UnexpectedEntry

**Comment by elahd** [comment]
Thanks for reporting this. The documentation for this API is atrocious -- there are a bunch of unpublished statuses and it doesn't look like anyone monitors api-support@platform.nyc.gov.

I ended up filing a Freedom of Information Law request with the city's IT department for the API source code (with a brief explanation). They replied with a full list of statuses, which is great.

I'll post a fix (with better error handling) soon.

**Comment by ghost** [comment]
> 

Thanks so much.  Good job on the Freedom of Information request!!!

**Comment by ghost** [comment]
Thank you for updating.  My main Home Assistant dashboard is much happier now.

**Comment by elahd** [comment]
Great! Out of curiosity, how are you displaying this integration on your dashboard? Would there be any value to having this integration work with Home Assistant calendars?

Calendar card: https://www.home-assistant.io/dashboards/calendar/
Calendar integration: https://www.home-assistant.io/integrations/calendar/

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/78881000/171701667-41a17f8b-377f-44ec-aa9d-6897ca2f3f17.png)

I use your integration along with the garbage integration in custom mushroom cards on the main dashboard.  The alternate side info is on another dashboard.

Calendar- ABSOLUTELY!  I would like to create trigger-based automations from this info. In the release that dropped yesterday (https://www.home-assistant.io/blog/2022/06/01/release-20226/#calendar-triggers-with-offsets), we now have offsets.

**Comment by elahd** [comment]
Awesome -- thanks for the input!

**Comment by elahd** [comment]
@fhc115 Update to v0.1.2.
